### ISSUE TITLE
ValueError: current limit exceeds maximum limit

### ISSUE THREAD

**Issue by eternalbluei** [SourceCode-AI/aura#24]
```
(aura)  blue@BluedeMacBook-Pro  ~/Downloads/aura-dev  aura scan /Users/blue/Documents/Malicious/dataset/pypi_unzip/raw-tool/2.0.1/raw_tool-2.0.1/setup.py
Traceback (most recent call last):
  File "/Users/blue/opt/anaconda3/envs/aura/bin/aura", line 5, in <module>
    from aura.cli import main
  File "/Users/blue/opt/anaconda3/envs/aura/lib/python3.10/site-packages/aura/cli.py", line 16, in <module>
    from . import commands
  File "/Users/blue/opt/anaconda3/envs/aura/lib/python3.10/site-packages/aura/commands.py", line 16, in <module>
    from .package_analyzer import Analyzer
  File "/Users/blue/opt/anaconda3/envs/aura/lib/python3.10/site-packages/aura/package_analyzer.py", line 13, in <module>
    from . import utils
  File "/Users/blue/opt/anaconda3/envs/aura/lib/python3.10/site-packages/aura/utils.py", line 21, in <module>
    from . import config
  File "/Users/blue/opt/anaconda3/envs/aura/lib/python3.10/site-packages/aura/config.py", line 310, in <module>
    load_config()
  File "/Users/blue/opt/anaconda3/envs/aura/lib/python3.10/site-packages/aura/config.py", line 240, in load_config
    resource.setrlimit(resource.RLIMIT_RSS, (rss, rss))
ValueError: current limit exceeds maximum limit
```

Why? How to deal with the error?

**Comment by zrk233** [comment]
Hello, I am an undergraduate student. Your code (WAF) has been referenced in the graduation design, but the code has been reporting errors. May I contact you personally, either qq or WeChat

**Comment by lxyeternal** [comment]
> 

WAF code can normal run. In 2021, a girl used waf code as the graduation design. My development environment is MacOS. My wechat account is lxy_limerence.

**Comment by RootLUG** [comment]
Hello,
for the error I would suggest disabling the RSS in the yaml config, some MacOS version behaves incorrectly for this or have wrong defaults. The RSS in general is not needed and it is used as a safety mechanism as sometimes if the code is very complex it can consume a lot of memory or when running in a server for automated code processing.

The option to disable the RSS is called `rlimit-memory` in the config

I do not have Wechat neither qq but if you want to contact me personally then I would suggest email: admin@sourcecode.ai

**Comment by lxyeternal** [comment]
Thanks, I resolve the issue successfully.

**Comment by zrk233** [comment]
> > 
> 
> WAF代码可以正常运行。2021年，一个女孩用waf代码作为毕业设计。我的开发环境是 MacOS。我的微信账号lxy_limerence。

Excuse me, I have already contacted you on WeChat. Please apply through a friend

**Comment by zrk233** [comment]
Excuse me, I have sent a WeChat friend application, please pass it.



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/27/2023 10:41 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [SourceCode-AI/aura] ValueError: current limit exceeds maximum limit (Issue #24) |

WAF code can normal run. In 2021, a girl used waf code as the graduation design. My development environment is MacOS. My wechat account is lxy_limerence.
