### ISSUE TITLE
Your SQLite installation doesn't have support for JSON1

### ISSUE THREAD

**Issue by lxyeternal** [SourceCode-AI/aura#33]
When running aura.cli on Ubuntu 22.04, MacOS 14.7, and Windows 11, the following error message consistently appears:

```
2024-09-24 15:44:09,093 - aura.cli - ERROR - Your SQLite installation doesn't have support for JSON1, compile opts: ATOMIC_INTRINSICS=1, COMPILER=clang-14.0.6, DEFAULT_AUTOVACUUM, DEFAULT_CACHE_SIZE=-2000, DEFAULT_FILE_FORMAT=4, DEFAULT_JOURNAL_SIZE_LIMIT=-1, DEFAULT_MMAP_SIZE=0, DEFAULT_PAGE_SIZE=4096, DEFAULT_PCACHE_INITSZ=20, DEFAULT_RECURSIVE_TRIGGERS, DEFAULT_SECTOR_SIZE=4096, DEFAULT_SYNCHRONOUS=2, DEFAULT_WAL_AUTOCHECKPOINT=1000, DEFAULT_WAL_SYNCHRONOUS=2, DEFAULT_WORKER_THREADS=0, DIRECT_OVERFLOW_READ, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB, ENABLE_FTS3, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4, ENABLE_FTS5, ENABLE_GEOPOLY, ENABLE_MATH_FUNCTIONS, ENABLE_RTREE, ENABLE_UNLOCK_NOTIFY, MALLOC_SOFT_LIMIT=1024, MAX_ATTACHED=10, MAX_COLUMN=2000, MAX_COMPOUND_SELECT=500, MAX_DEFAULT_PAGE_SIZE=8192, MAX_EXPR_DEPTH=10000, MAX_FUNCTION_ARG=127, MAX_LENGTH=1000000000, MAX_LIKE_PATTERN_LENGTH=50000, MAX_MMAP_SIZE=0x7fff0000, MAX_PAGE_COUNT=0xfffffffe, MAX_PAGE_SIZE=65536, MAX_SQL_LENGTH=1000000000, MAX_TRIGGER_DEPTH=1000, MAX_VARIABLE_NUMBER=250000, MAX_VDBE_OP=250000000, MAX_WORKER_THREADS=8, MUTEX_PTHREADS, SECURE_DELETE, SYSTEM_MALLOC, TEMP_STORE=1, THREADSAFE=1
Traceback (most recent call last):
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/aura_security-2.1-py3.9.egg/aura/cli.py", line 113, in scan
    commands.scan_uri(uri, metadata=meta, download_only=download_only)
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/aura_security-2.1-py3.9.egg/aura/commands.py", line 87, in scan_uri
    formatters = [ScanOutputBase.from_uri(x, opts=metadata.get("output_opts")) for x in output_format]
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/aura_security-2.1-py3.9.egg/aura/commands.py", line 87, in <listcomp>
    formatters = [ScanOutputBase.from_uri(x, opts=metadata.get("output_opts")) for x in output_format]
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/aura_security-2.1-py3.9.egg/aura/output/base.py", line 90, in from_uri
    fmt_class = cls.get_format(uri, parsed)
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/aura_security-2.1-py3.9.egg/aura/output/base.py", line 52, in get_format
    for fmt_name, fmt in cls.get_all_output_formats().items():
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/aura_security-2.1-py3.9.egg/aura/output/base.py", line 42, in get_all_output_formats
    handler = x.load()
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2781, in load
    return self.resolve()
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2787, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/aura_security-2.1-py3.9.egg/aura/output/sqlite.py", line 292, in <module>
    check_sqlite_support()
  File "/Users/blue/anaconda3/envs/python39/lib/python3.9/site-packages/aura_security-2.1-py3.9.egg/aura/output/sqlite.py", line 24, in check_sqlite_support
    raise PluginDisabled(
aura.exceptions.PluginDisabled: ("Your SQLite installation doesn't have support for JSON1, compile opts: ATOMIC_INTRINSICS=1, COMPILER=clang-14.0.6, DEFAULT_AUTOVACUUM, DEFAULT_CACHE_SIZE=-2000, DEFAULT_FILE_FORMAT=4, DEFAULT_JOURNAL_SIZE_LIMIT=-1, DEFAULT_MMAP_SIZE=0, DEFAULT_PAGE_SIZE=4096, DEFAULT_PCACHE_INITSZ=20, DEFAULT_RECURSIVE_TRIGGERS, DEFAULT_SECTOR_SIZE=4096, DEFAULT_SYNCHRONOUS=2, DEFAULT_WAL_AUTOCHECKPOINT=1000, DEFAULT_WAL_SYNCHRONOUS=2, DEFAULT_WORKER_THREADS=0, DIRECT_OVERFLOW_READ, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB, ENABLE_FTS3, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4, ENABLE_FTS5, ENABLE_GEOPOLY, ENABLE_MATH_FUNCTIONS, ENABLE_RTREE, ENABLE_UNLOCK_NOTIFY, MALLOC_SOFT_LIMIT=1024, MAX_ATTACHED=10, MAX_COLUMN=2000, MAX_COMPOUND_SELECT=500, MAX_DEFAULT_PAGE_SIZE=8192, MAX_EXPR_DEPTH=10000, MAX_FUNCTION_ARG=127, MAX_LENGTH=1000000000, MAX_LIKE_PATTERN_LENGTH=50000, MAX_MMAP_SIZE=0x7fff0000, MAX_PAGE_COUNT=0xfffffffe, MAX_PAGE_SIZE=65536, MAX_SQL_LENGTH=1000000000, MAX_TRIGGER_DEPTH=1000, MAX_VARIABLE_NUMBER=250000, MAX_VDBE_OP=250000000, MAX_WORKER_THREADS=8, MUTEX_PTHREADS, SECURE_DELETE, SYSTEM_MALLOC, TEMP_STORE=1, THREADSAFE=1", '/Users/blue/Downloads/aura-security-2.1', {'format': ('plain',), 'analyzers': (), 'source': 'cli', 'fork': False, 'output_opts': {'tags': (), 'verbosity': 2}})
Your SQLite installation doesn't have support for JSON1, compile opts: ATOMIC_INTRINSICS=1, COMPILER=clang-14.0.6, DEFAULT_AUTOVACUUM, DEFAULT_CACHE_SIZE=-2000, DEFAULT_FILE_FORMAT=4, DEFAULT_JOURNAL_SIZE_LIMIT=-1, DEFAULT_MMAP_SIZE=0, DEFAULT_PAGE_SIZE=4096, DEFAULT_PCACHE_INITSZ=20, DEFAULT_RECURSIVE_TRIGGERS, DEFAULT_SECTOR_SIZE=4096, DEFAULT_SYNCHRONOUS=2, DEFAULT_WAL_AUTOCHECKPOINT=1000, DEFAULT_WAL_SYNCHRONOUS=2, DEFAULT_WORKER_THREADS=0, DIRECT_OVERFLOW_READ, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB, ENABLE_FTS3, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4, ENABLE_FTS5, ENABLE_GEOPOLY, ENABLE_MATH_FUNCTIONS, ENABLE_RTREE, ENABLE_UNLOCK_NOTIFY, MALLOC_SOFT_LIMIT=1024, MAX_ATTACHED=10, MAX_COLUMN=2000, MAX_COMPOUND_SELECT=500, MAX_DEFAULT_PAGE_SIZE=8192, MAX_EXPR_DEPTH=10000, MAX_FUNCTION_ARG=127, MAX_LENGTH=1000000000, MAX_LIKE_PATTERN_LENGTH=50000, MAX_MMAP_SIZE=0x7fff0000, MAX_PAGE_COUNT=0xfffffffe, MAX_PAGE_SIZE=65536, MAX_SQL_LENGTH=1000000000, MAX_TRIGGER_DEPTH=1000, MAX_VARIABLE_NUMBER=250000, MAX_VDBE_OP=250000000, MAX_WORKER_THREADS=8, MUTEX_PTHREADS, SECURE_DELETE, SYSTEM_MALLOC, TEMP_STORE=1, THREADSAFE=1
```

Operating Systems:

Ubuntu 22.04 LTS
MacOS 14.7
Windows 11
Python Version: 3.9.19

**Comment by lxyeternal** [comment]
I have already addressed this issue.
